CDCgov/prime-public-health-data-infrastructure

docs/getting_started.md

This pull request makes a few changes to the `getting_started.md` file:
* Adds more details or further clarifies points in various sections.  
* Rearranges some of the sections to provide a better flow, starting with a more general review of using VS Code and then diving into the specifics of working with Python and Java.  
* Removes references to 'golden path' as this is biased language in my opinion. The language implies that using a Mac is better than using Windows for development on this project, but the tech stack is platform agnostic.  
* Adds details on developing in Java and Kotlin, including setting up environment variables, defining dependencies, and installing necessary software, such as Maven.  
Not necessary, as the doc can be view in the PR
* Do others agree that the …

Update Getting Started Doc to Include Java/Kotlin

---

.github/workflows/test.yaml

Fixes https://app.clickup.com/t/2fr7t8x
Scan the directory `src/FunctionApps` and look for directories containing a function app that needs to have tests run on it.
This will remove the need to update the workflow when a function app is added or removed.
This is done by looking into each top-level directory under `FunctionApps` for a file.  If a `requirements.txt` file exists, the directory is determined to have a python function app in it.  Java/Kotlin apps are contain a `pom.xml` file (the workflow currently only supports maven).  Lists of the found function apps are used to set the matrix of python and java apps to tests.
1. Add a new job that generates lists of function-app directory names and sets them as outputs
2. Make the unit test matrix jobs dependent on the new job
3. Use the …

[cu-2fr7t8x] Auto-detect function apps to test

---

src/FunctionApps/DSTP/pom.xml
src/FunctionApps/DSTP/src/main/kotlin/gov/cdc/prime/phdi/Utilities/HelperFunctions.kt

We have changed the authentication process with the FHIR server to use [Default Azure Credential](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python) as opposed to reading a client_id and client_secret from a local.settings.json file. This change is necessary in order to authenticate with the FHIR server in CDC Azure because the additional security measures that were recently implemented have removed access to client_id and client_secret. We also benefit from this change because Default Azure Credential abstracts the authentication process allowing our code to authenticate in the same way regardless of whether it is running locally or in the cloud. 
Beyond a re-write getAccessToken() changes have been made to pom.xml to …

Change getAccessToken() to authenticate via Default Azure Credential

---

docs/decisions/0007-pr-approval-requires-checks-to-pass.md
docs/decisions/0007-pr-approvals-require-checks-to-pass.md
docs/decisions/0008-merging-prs-requires-checks-to-pass.md

Pull Requests require both that all checks that have been implemented pass and that at least 1 developer approve the pull request. Unfortunately, there's no way to ensure that a developer is only approving pull requests that have passed all checks, which can result in an opportunity for developers to merge PRs with unsuccessful checks. This PR introduces two ADRs, which encompass two different solutions to this. I assume that one of the ADRs will be rejected in favor of the other, but I wanted to provide both as an option.
- Which of these seems like the best approach to ensuring bad merges don't take place?  
- Is there another option I'm not considering?

Add ADR requiring checks to pass before approvals are made

---

docs/decisions/0006-squash-merge-prs.md

This PR adds an ADR explaining our decision to use the Squash and Merge approach to merging PRs into main.
- Does everyone still agree with this approach? It was raised in a conversation by Graham and I believe only a couple people weighed in.  
- Do we need to explicitly describe any type of standards or expectations around the single commit message that is used for the merge?
- Are there other alternatives that should be listed as considered?

Add Squash and Merge ADR

---

docs/decisions/template.md

This PR updates the ADR template to explicitly provide a data format (YYYY-MM-DD) and list the Appendix section as optional. Of the 4 ADRs that have merged to date, 3 of the 4 followed these standards, but ADR 4 showed some variability, so I'm making these updates to make it more explicit what we're looking for in ADRs.

Explicitly state data format in ADR and make Appendix optional

---

docs/decisions/0004-working-with-fhir-data.md

I know ADRs should be immutable once approved or rejected, but this ADR was approved despite inconsistent formatting. Typically I'd let that go, but the title didn't even match the ADR given that the title was `0003 Working with FHIR Data` and this is ADR #4. Given that this needs to be changed, I'm taking the opportunity to also modify the date format to be consistent with the other ADRs.

Fix title and date format for ADR #4

---

src/FunctionApps/python/GenerateCSVs/__init__.py
src/FunctionApps/python/GenerateCSVs/elr.py
src/FunctionApps/python/tests/GenerateCSVs/assets/elr.json
src/FunctionApps/python/tests/GenerateCSVs/assets/observation.json
src/FunctionApps/python/tests/GenerateCSVs/test_elr.py
src/FunctionApps/python/tests/GenerateCSVs/test_main.py

This PR introduces the functionality needed for us to generate csv rows from ELR data. Using Dan's patient extractor function, this changeset extends that by identifying COVID related observations and incorporating relevant fields into the generated rows. Tests are included for the individual function.
Also, per slack discussion, the return type of all functions should be modified to a list of lists. I've done that for the ELR function and also set up the main functions (and tests) to work with that data type.

Add ELR parsing to CSVs

---

src/FunctionApps/python/IntakePipeline/__init__.py
src/FunctionApps/python/IntakePipeline/fhir.py
src/FunctionApps/python/tests/IntakePipeline/fhir_test.py
src/FunctionApps/python/tests/IntakePipeline/pipeline_test.py

This PR does two primary things:  
1. It modifies the `upload_bundle_to_fhir_server` function to no longer maintain its own access token using the credential manager. Instead, both the access token and the FHIR URL are passed into the function by the orchestrator. Tests were updated to reflect this.
2. Expands the coverage of the pipeline tests to also ensure the pipeline works for invalid messages. 
All tests pass when running `python -m pytest` and the code has been run locally to ensure that changes to `upload_bundle_to_fhir_server` didn't cause any obvious errors. The code appears to be working at a surface level as it was before the change.
Nothing specific. The changes mentioned in (1) are a result of feedback left in PR#86, and changes in (2) seem straightforward.

Refactor FHIR bundle upload and expand test coverage

---

src/FunctionApps/python/GenerateCSVs/elr.py

Simple addition of some error handling. We should keep in mind that the rows in the ELR CSV are:
1. A mixture of ELR results and other observations resources.
2. Not necessarily all ELR results.
3. Not all observation resources.

Error handling to ignore observations without a key of value 'code'.

---

src/FunctionApps/python/IntakePipeline/__init__.py
src/FunctionApps/python/IntakePipeline/conversion.py
src/FunctionApps/python/IntakePipeline/fhir.py
src/FunctionApps/python/IntakePipeline/transform.py
src/FunctionApps/python/tests/IntakePipeline/conversion_test.py
src/FunctionApps/python/tests/IntakePipeline/pipeline_test.py

Previously, we were sending function app messages to the standard logs, which ended up stored locally on the functionapp's service app (linux container).  This wasn't OK, because the output could contain PII, and the log file location is unencrypted.  
Now, we are returning the HTTP status code and accompanying return value.  The code that calls the conversion function stores the response information in a (secure) blob location.  
Previously, if the number of address elements from an incoming element did not equal the number of elements in the standardized address, it resulted in a address key error.  This has been fixed.
Tests have been updated to reflect that successful responses should contain a FHIR bundle (resourceType = "Bundle").  The error response is no longer has special …

Secure log output

---

operations/app/terraform/modules/storage/data.tf

In an effort to bring in the new data that VA is providing, we want to be able to point the Azure Data Factory to the `bronze-additional-records` container. In the future, we'll likely want to point it back to `bronze` and ingest everything into a single storage container, but for now, it's probably best to keep the new data separate.

Give ADF access to bronze-additional-records container

---

src/FunctionApps/python/requirements.txt

Now that #109 has been merged we can point the path used in `IntakePipeline` to load `phdi_building_blocks` `back to main`.

Point IntakePipeline to load phdi_building_blocks from main.

---

src/FunctionApps/python/FhirServerExport/__init__.py
src/FunctionApps/python/tests/FhirServerExport/test_main.py
src/lib/phdi-building-blocks/phdi_building_blocks/fhir.py
src/lib/phdi-building-blocks/tests/test_fhir.py

Update FHIR export to specify a target container to which export files are written.
Additional changes
* Fix how access token is passed to export function
* Improve logging
* Update terraform - add new fhir-export container

Specify container on export

---

docs/security/data-access.md
operations/app/terraform/modules/storage/data.tf
src/FunctionApps/python/FhirServerExport/README.md
src/FunctionApps/python/FhirServerExport/__init__.py
src/FunctionApps/python/tests/FhirServerExport/test_main.py

* Rather than allowing the target container for export files to be specified as part of the export request, configure it in the function app serttings.
* Add new fhir-exports default export storage container to terraform

Configure container in functionapp

---

.github/workflows/deployDev.yaml
.github/workflows/deployTest.yaml

Resolves [this ticket](https://reportstream-service-request.clickup.com/t/29av3gn)
This PR creates two new GitHub Actions, one for deploying to `dev` and another for deploying to `test`. They are pretty simple, just logging into Azure/Terraform using the creds stored for CI, and running terraform apply. We will need to merge this PR before we can test running the actions, which will create the actions in [the UI here](https://github.com/CDCgov/prime-public-health-data-infrastructure/actions), then any further changes can be tested in further PRs before merging, since branches can be specified for existing actions.

Add GitHub Actions for deployment

---

.github/workflows/test.yaml

Since $GITHUB_HEAD_REF is only available in pull requests, use the `github` [context object](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) to get the current branch instead for the testing workflow. I _think_ this should be available on the main branch as well, but we will have to merge to find out.

Use github context to get current branch for testing workflow

---

src/lib/phdi-building-blocks/phdi_building_blocks/schemas.py
src/lib/phdi-building-blocks/tests/test_schemas.py

[Link](https://reportstream-service-request.clickup.com/t/2h264r0) to ticket
In addition to parquet, the application will now support CSV when writing schema tables. This allows epis to have an additional file type to do analysis on. Tests are also included in this PR

Ability to write schemas to CSV

---

src/lib/phdi-building-blocks/phdi_building_blocks/schemas.py

This PR addresses an issue where non-string fields (e.g. latitude or longitude) that were missing for a resource were being defaulted to `""` instead of `None`. The issue was cashing the entire pipeline to crash when trying to write the data to a Parquet file because Parquet was trying to convert the string to a double. By setting the default value for missing fields to `None`, Parquet is able to properly handle the missing data.
This has been tested in a Jupyter notebook using Patient data that included latitude and longitude. I first ran the data through the code as written, observed that it failed, and then modified the `apply_schema_to_resource` function locally to use `None` instead of `""`. I ran the data through the updated version of the code and observed that it worked.

Default to None for Missing Values in FHIR to Data Mart ETL Pipeline

---

src/FunctionApps/python/IntakePipeline/__init__.py
src/FunctionApps/python/tests/IntakePipeline/test_pipeline.py
src/lib/phdi-building-blocks/phdi_building_blocks/azure.py
src/lib/phdi-building-blocks/phdi_building_blocks/conversion.py
src/lib/phdi-building-blocks/phdi_building_blocks/fhir.py
src/lib/phdi-building-blocks/tests/test_azure.py
src/lib/phdi-building-blocks/tests/test_conversion.py
src/lib/phdi-building-blocks/tests/test_fhir.py

When uploading content to the FHIR server during resource ingestion, batches of resources are posted to the FHIR server.  Two error scenarios are:
* The whole batch transaction fails, and the FHIR server returns an HTTP error code.
* The top level batch transaction succeeds, but individual entries within the batch fail.
Previously, the system would report an entry in the error log to indicate when a whole batch failed.  Individual entry failures were ignored.  The error message did not contain information about the content of the failure.
Now, both top level, and individual entry failures are recorded in the error log in the core phdi_building_blocks library code.  
In addition, the IntakePipeline azure function uploads request and response (or individual failed entry in the case of …

Enhanced logging for FhirServer Upload

---

operations/app/terraform/modules/storage/acl.tf
operations/app/terraform/modules/storage/data.tf
operations/app/terraform/modules/storage/~inputs.tf
operations/app/terraform/vars/dev/main.tf
operations/app/terraform/vars/dev/variables.tf
operations/app/terraform/vars/test/main.tf
operations/app/terraform/vars/test/variables.tf

This PR removes some data items from our terraform `storage` module, which attempt to read the `CT-PRIMEIngestion-AZ-Contributors` group from Active Directory in Azure, so that it can get the groups ID and set it as the owner of our `pi_datasa` storage accounts. From what I can tell, this is not really necessary, as our `SU` Azure users already have the necessary permissions to be able to interact with all storage accounts in our resource groups, regardless of owners. The reason for removing this is because CDC won't give a service principal permissions to read from Active Directory, so including this will prevent us from properly implementing CD.

Remove AD data from terraform storage module
