CDCgov/prime-public-health-data-infrastructure

notebooks/Geocoding Proof of Concept.ipynb
https://app.clickup.com/t/1vz57f4
=> [CLICKUP-1vz57f4] Adding Proof of Concept for Notebook using Geocoder

operations/app/terraform/modules/log_analytics_workspace/main.tf
Including change made by Azure behind the scenes to keep TF clean
=> adding metric change that Azure forced behind the scenes

docs/README.md, docs/decisions/0001-record-architecture-decisions.md, docs/decisions/README.md, docs/decisions/template.md
A meta-proposal to use Architectural Decision Records to record decisions on our project﻿
=> Adding meta-proposal to use Architectural Decision Records

docs/decisions/0002-assume-data-engineering-architecture.md
See below proposal to use the book Data Engineering with Apache Spark, Delta Lake, and Lakehouse as the basis for our system architecture going forward, and where there are deviations, conducting time-limited investigations to explore alternatives
=> Decision: Use Data Engineering With Spark book as the basis for our architecture

operations/app/terraform/modules/data_factory/main.tf
This PR imports the demo pipeline from within the Data Factory into Terraform.
[Line 127](https://github.com/CDCgov/prime-public-health-data-infrastructure/compare/josiahsiegel/adf-pipeline-init?expand=1#diff-52261c3417d8bbc2a9b909f489bbf2b7a630ba8293481cae763dbad607488456R127) shows how pipelines, which can be anywhere from simple to extremely complex are represented as a json object. Any changes made in the Data Factory can be scripted for TF by running `terraform state show module.data_factory.azurerm_data_factory_pipeline.transfer_files` or `terraform plan`
=> import data factory pipeline

.flake8, .github/workflows/test.yaml, .gitignore, src/FunctionApps/PHDISmartyStreetsTest/tests/test_geocode_address.py
This PR adds a workflow that will run when pull requests are created.  It will run:
* Tests on python code using `pytest`
* Tests and other checks on kotlin code with `mvn verify`
* Formatting and style checks on python code
* Formatting checks on terraform
For this workflow to complete successfully, this depends on merging the following branches:
* `task-25qr6zp` (add DSTP function app)
* `bmaden-usds/format` (apply python and terraform formatting)
An example completed run: https://github.com/CDCgov/prime-public-health-data-infrastructure/actions/runs/1820655925
Fixes https://app.clickup.com/t/28ymg61
=> Add workflow to execute tests and code checks

docs/getting_started.md
Adds in a brief description of writing and running tests for Java and Kotlin in VS Code. Testing Azure apps is currently not discussed.
N/A as you can view the updated doc in the PR
* Are you able to follow what I'm saying and understand it?
* Would you be able to replicate these steps to write your own tests?
* Is there anything else that should be added?
=> Add documentation about writing and running tests in Java and Kotlin

docs/decisions/0003-caching-layer.md
Open a discussion about the outcome of the caching spikes (#35 , #36)
=> Add draft ADR for caching

src/FunctionApps/PITest_FunctionApp/tests/test_decrypt_function.py
Should now work in vscode and cli - :crossed_fingers: for github actions
=> Use pathlib instead of importlib for test fixtures

.github/workflows/test.yaml, src/lib/phdi-transforms/README.md, src/lib/phdi-transforms/poetry.lock, src/lib/phdi-transforms/pyproject.toml, src/lib/phdi-transforms/requirements.txt, src/lib/phdi-transforms/requirements_dev.txt
The plan is to squash this back down to clean up the commit history and force push after standup as long as everybody's good with it
=> Revert to using poetry

docs/decisions/0005-adr-version-control.md
This ADR proposes a method by which existing ADRs are deprecated and superseded by new ADRs.
I like the approach in the alternative options section more than the proposed solution, but the proposed solution is closer to the spirt of ADRs. I would be interested in hearing others' thoughts about the two approaches.
=> ADR for superseding previous ADRs

src/FunctionApps/python/IntakePipeline/README.md, src/FunctionApps/python/IntakePipeline/__init__.py, src/FunctionApps/python/IntakePipeline/transform.py, src/FunctionApps/python/requirements.txt, src/FunctionApps/python/tests/IntakePipeline/assets/patient_bundle.json, src/FunctionApps/python/tests/IntakePipeline/pipeline_test.py, src/FunctionApps/python/tests/IntakePipeline/transform_test.py
=> Implement patient transforms

src/FunctionApps/python/IntakePipeline/README.md, src/FunctionApps/python/IntakePipeline/__init__.py, src/FunctionApps/python/IntakePipeline/fhir.py, src/FunctionApps/python/tests/IntakePipeline/fhir_test.py, src/FunctionApps/python/tests/IntakePipeline/pipeline_test.py
Stores transformed bundles back into blob storage
=> Add blob store output

src/FunctionApps/python/IntakePipeline/fhir.py, src/FunctionApps/python/IntakePipeline/linkage.py, src/FunctionApps/python/IntakePipeline/transform.py, src/FunctionApps/python/tests/IntakePipeline/linkage_test.py, src/FunctionApps/python/tests/IntakePipeline/transform_test.py, src/lib/phdi-transforms/phdi_transforms/geo.py
* Basically just covering for missing data we didn't anticipate
=> Misc pipeline fixes

src/FunctionApps/python/IntakePipeline/fhir.py
#77 introduced a thing that caused the client to error out, this reverts just that part
=> roll back edit on get_blob_client

src/FunctionApps/python/GenerateCSVs/vxu.py, src/FunctionApps/python/tests/GenerateCSVs/assets/vxu.json, src/FunctionApps/python/tests/GenerateCSVs/test_vxu.py
=> Add VXU Parsing for CSVs

.github/CODEOWNERS
This PR just keeps the CODEOWNERS up to date
=> Removing Graham and Jesse as code owners

.github/workflows/test.yaml
We no longer have Java code in our repository.  Remove unused workflow steps related to Java.
=> Remove unused java-related workflow steps

src/FunctionApps/python/requirements.txt
Repoint phdi building blocks dependency in requirements.txt to main
=> Repoint requirements.txt to main

src/lib/phdi-building-blocks/phdi_building_blocks/standardize.py, src/lib/phdi-building-blocks/poetry.lock, src/lib/phdi-building-blocks/pyproject.toml, src/lib/phdi-building-blocks/tests/test_standardize.py
This PR aims to make our phone number standardization process more robust with a focus on being able to handle international phone numbers that may or may not include country codes.
=> Add updated phone number standardization, supporting functions, and testing

.github/workflows/test.yaml
See this [StackOverflow answer](https://stackoverflow.com/a/71158878/5365414)
=> Fallback to github.ref_name when github.head_ref is not available

docs/getting_started.md
- Updated the list of laptops that are supported as Nick Clyde mentioned Apple Silicon chips work fine. 
- Added poetry installation
- Updated how to run tests
- Included how to get access to the repo
=> Added new steps for local testing. Poetry installation

.github/workflows/deployDev.yaml, .github/workflows/deployTest.yaml
This will enable continuous deployment for the project! On every merge to main, it will trigger a deploy to the dev environment in CDC Azure. When that deploy is successful, it will trigger a deploy to the test environment. This will keep our code fully up to date in CDC Azure.
=> Enable continuous deployment
